// Generated by gencpp from file rt_gene/MSG_SubjectImagesList.msg
// DO NOT EDIT!


#ifndef RT_GENE_MESSAGE_MSG_SUBJECTIMAGESLIST_H
#define RT_GENE_MESSAGE_MSG_SUBJECTIMAGESLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rt_gene/MSG_SubjectImages.h>

namespace rt_gene
{
template <class ContainerAllocator>
struct MSG_SubjectImagesList_
{
  typedef MSG_SubjectImagesList_<ContainerAllocator> Type;

  MSG_SubjectImagesList_()
    : header()
    , subjects()  {
    }
  MSG_SubjectImagesList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , subjects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::rt_gene::MSG_SubjectImages_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rt_gene::MSG_SubjectImages_<ContainerAllocator> >::other >  _subjects_type;
  _subjects_type subjects;





  typedef boost::shared_ptr< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> const> ConstPtr;

}; // struct MSG_SubjectImagesList_

typedef ::rt_gene::MSG_SubjectImagesList_<std::allocator<void> > MSG_SubjectImagesList;

typedef boost::shared_ptr< ::rt_gene::MSG_SubjectImagesList > MSG_SubjectImagesListPtr;
typedef boost::shared_ptr< ::rt_gene::MSG_SubjectImagesList const> MSG_SubjectImagesListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rt_gene

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'rt_gene': ['/home/godfrey/wheelchair/src/rt_gene/rt_gene/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bca8076b86dc37b0d0f1350d2b30ab4e";
  }

  static const char* value(const ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbca8076b86dc37b0ULL;
  static const uint64_t static_value2 = 0xd0f1350d2b30ab4eULL;
};

template<class ContainerAllocator>
struct DataType< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rt_gene/MSG_SubjectImagesList";
  }

  static const char* value(const ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"MSG_SubjectImages[] subjects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: rt_gene/MSG_SubjectImages\n"
"string subject_id\n"
"sensor_msgs/Image face_img\n"
"sensor_msgs/Image right_eye_img\n"
"sensor_msgs/Image left_eye_img\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.subjects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MSG_SubjectImagesList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rt_gene::MSG_SubjectImagesList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "subjects[]" << std::endl;
    for (size_t i = 0; i < v.subjects.size(); ++i)
    {
      s << indent << "  subjects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rt_gene::MSG_SubjectImages_<ContainerAllocator> >::stream(s, indent + "    ", v.subjects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RT_GENE_MESSAGE_MSG_SUBJECTIMAGESLIST_H
